apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-pod
  template:
    metadata:
      labels:
        app: catalog-pod     # Pod labels
    spec:
      containers:
      - name: catalog-container
        image: jschristophe/accorbooking-catalog-api:v1.2 #test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  #loadBalancerIP: 52.143.154.218
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: catalog-pod